"""create initial tables

Revision ID: b81bce4d0a8d
Revises: 
Create Date: 2026-04-23 03:35:56.502567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b81bce4d0a8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('hourly_stats',
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('hour', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('uptime_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_response_ms', sa.Integer(), nullable=True),
    sa.Column('p95_response_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['monitored_urls.id'], ),
    sa.PrimaryKeyConstraint('url_id', 'hour')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('checks_failed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['monitored_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['monitored_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_checks')
    op.drop_table('incidents')
    op.drop_table('hourly_stats')
    op.drop_table('monitored_urls')
    # ### end Alembic commands ###
